#!/bin/bash

set -e

AGENCY="MTA"
WORKDIR="${AGENCY,,}_workdir"

rm -rf "$WORKDIR"
mkdir -p "$WORKDIR"

./bin/sort_GTFS_shapes < "data/${AGENCY}/shapes.txt" > "${WORKDIR}/${AGENCY,,}.shapes.sorted.txt"

./bin/gtfs_shapes_to_ndjson < "${WORKDIR}/${AGENCY,,}.shapes.sorted.txt" |
  ./bin/ndjson_to_geojson > "${WORKDIR}/${AGENCY,,}.shapes.geojson"

./bin/runSharedStreets \
  --shapesGeoJSON "${WORKDIR}/${AGENCY,,}.shapes.geojson" \
  --outputDir "${WORKDIR}/shst" --clean

./bin/concatShStMatchesIntoNDJSON "${WORKDIR}/shst" > "${WORKDIR}/${AGENCY,,}.matched.ndjson"
./bin/ndjson_to_geojson < "${WORKDIR}/${AGENCY,,}.matched.ndjson" > "${WORKDIR}/${AGENCY,,}.matched.geojson"

./bin/combineSharedStreetMatchedGTFSShapesChunks < "${WORKDIR}/${AGENCY,,}.matched.ndjson" > "${WORKDIR}/${AGENCY,,}.matched.combined.ndjson"

./bin/splitShStMatchedFeatureCollectionIntoSeparateFiles --outputDir "${WORKDIR}/shape_geojsons" < "${WORKDIR}/${AGENCY,,}.matched.combined.ndjson"

