#!/bin/bash

set -e

WORKDIR='workdir'

rm -rf "$WORKDIR"
# mkdir "$WORKDIR"

./bin/sort_GTFS_shapes < data/CDTA/shapes.txt > "${WORKDIR}/cdta.shapes.sorted.txt"

./bin/gtfs_shapes_to_ndjson < "${WORKDIR}/cdta.shapes.sorted.txt" |
  ./bin/ndjson_to_geojson > "${WORKDIR}/cdta.shapes.geojson"

./bin/runSharedStreets \
  --shapesGeoJSON "${WORKDIR}/cdta.shapes.geojson" \
  --outputDir "${WORKDIR}/shst" --clean

./bin/concatShStMatchesIntoNDJSON "${WORKDIR}/shst" > "${WORKDIR}/cdta.matched.ndjson"

./bin/combineSharedStreetMatchedGTFSShapesChunks < "${WORKDIR}/cdta.matched.ndjson" > "${WORKDIR}/cdta.matched.combined.ndjson"

./bin/splitShStMatchedFeatureCollectionIntoSeparateFiles --outputDir "${WORKDIR}/shape_geojsons" < "${WORKDIR}/cdta.matched.combined.ndjson"
